First deliverable
amilcaralex97/academy-go-q42021 pull request #1
Opened 2021-11-13 04:24 UTC by amilcaralex97

First Deliverable:

Error handling WIP
Endpoints:
localhost:3000/characters (done)
localhost:3000/characters/:id (WIP)

2021-11-18 15:35 UTC, davidcdorbecker requested changes

2021-11-18 15:35 UTC, davidcdorbecker commented on app/interfaces/characterController.go
> +	characterID, _ := strconv.Atoi(r.URL.Query().Get("id"))
Aquí podríamos manejar el error, en caso de haber, podemos regresar un http.StatusBadRequest

2021-11-18 15:35 UTC, davidcdorbecker commented on app/common/csvParser.go
> +        log.Fatal("Unable to read input file " + filePath, err)
Podemos propagar estos errores para manejarlos hasta el controlador y devolver un http.StatusInternalServerError

2021-11-18 15:35 UTC, davidcdorbecker commented on app/common/csvParser.go
> +func CreateCharacterList(data [][]string) []domain.Character {
El CharacterList estaría mejor dentro del dominio de Characters, ya que por lo que veo este archivo es para leer el csv

2021-11-18 15:35 UTC, davidcdorbecker commented on app/infrastructure/router.go
> +		log.Printf("%s", err)
Aquí podemos hacer un panic, ya que si no puede servir a ese puerto no se podría levantar el servicio

2021-11-18 15:35 UTC, davidcdorbecker commented on app/interfaces/characterController.go
> +	// if err != nil  {
Podemos manejar este error propagandolo desde el csv

2021-11-18 15:35 UTC, davidcdorbecker commented on app/usecases/characterRepository.go
> +	data := common.ReadCsvFile("/home/amilcar/Documents/Projects/go-project/app/resources/characters.csv")
el path podemos manejarlo como constante, para evitar repetirlo en la línea 21

2021-11-18 15:35 UTC, davidcdorbecker commented on app/usecases/characterRepository.go
> +		fmt.Println(k, ' ', v)
Faltó la lógica para filtar por id aquí

2021-11-28 23:04 UTC, amilcaralex97 commented
Port fix pending

2021-11-28 23:04 UTC, merged